### ISSUE TITLE
Package is missing from Flathub

### ISSUE THREAD

**Issue by RiQuY** [flathub/org.freedesktop.Platform.VulkanLayer.OBSVkCapture#25] opened 2023-02-09 09:38 UTC
Package no longer exists on Flathub.
- https://flathub.org/apps/details/org.freedesktop.Platform.VulkanLayer.OBSVkCapture

![imagen](https://user-images.githubusercontent.com/26349954/217774827-0dbd0475-2aa1-423c-9952-ae8ddb0439fd.png)

**Comment by SuNNjek** [comment] 2023-02-09 15:42
Closing as it is a duplicate of #3 and https://github.com/flathub/com.obsproject.Studio.Plugin.OBSVkCapture/issues/16

**Closed by SuNNjek** 2023-02-09 15:42 UTC
